name: Instagram & Telegram Bot

on:
  schedule:
    # Kjører hver dag kl. 10:00 UTC (12:00 norsk tid)
    - cron: '0 10 * * *'
  workflow_dispatch:  # Lar deg kjøre manuelt

jobs:
  post_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut repository
        uses: actions/checkout@v3

      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Installer dependencies direkte
        run: |
          python -m pip install --upgrade pip
          pip install openai requests pillow

      - name: Kjør bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LONG_LIVED_USER_TOKEN: ${{ secrets.LONG_LIVED_USER_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          INSTAGRAM_APP_ID: ${{ secrets.INSTAGRAM_APP_ID }}
          INSTAGRAM_APP_SECRET: ${{ secrets.INSTAGRAM_APP_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python bot_script.py
