name: Run gro.py daily

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-gro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai requests pillow

      - name: Run gro.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LONG_LIVED_USER_TOKEN: ${{ secrets.LONG_LIVED_USER_TOKEN }}
          PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}   # optional; ok if blank
          PAGE_ID: ${{ secrets.PAGE_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python gro.py
