name: Daily Gro Post

on:
  schedule:
    # Kjør daglig kl 08:00 UTC (tilpass tidssone om nødvendig)
    - cron: '0 8 * * *'
  workflow_dispatch: # lar deg kjøre manuelt

jobs:
  post_daily:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
      PAGE_ID: ${{ secrets.PAGE_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai pillow requests

      - name: Run Gro Script
        run: python gro.py
