name: Run gro.py

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"  # kjører hver dag kl 08:00 UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v4

      - name: Sett opp Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer avhengigheter
        run: |
          python -m pip install --upgrade pip
          pip install requests openai

      - name: Kjør gro.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LONG_LIVED_USER_TOKEN: ${{ secrets.LONG_LIVED_USER_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python gro.py
